name: deploy to prd-xserver

# on: ["pull_request"]
on:
  push:
    tags:
      - "stg.v.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy env
        run: |
          cp src/.env.example src/.env
      - name: dokcer-compose up
        run: |
          docker compose up -d
      - name: npm ci
        run: |
          docker compose exec app npm ci
      - name: npm build
        run: |
          docker compose exec app npm run build
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.STG_FTP_SERVER }}
          username: ${{ secrets.STG_FTP_USERNAME }}
          password: ${{ secrets.STG_FTP_PASSWORD }}
          local-dir: ./src/
          server-dir: ./
          exclude: |
            **/node_modules/**
            **/resources/js/**
            **/vendor/**
            .env
            tests/**
            storage/**
            *.log
            *.cache
